USE PeopleTracker
GO

/****** Object:  Table dbo.Email    Script Date: 5/29/2018 6:54:08 PM ******/
IF OBJECT_ID('dbo.Email', 'U') IS NOT NULL
BEGIN
  ALTER TABLE dbo.Email DROP CONSTRAINT FK_Email_EmailType
	DROP TABLE dbo.Email
END
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.Email(
	EmailId int IDENTITY(1,1) NOT NULL,
	EmailAddress nvarchar(1024) NOT NULL,
	EmailTypeId int NOT NULL,
	isPrimary bit NOT NULL,
 CONSTRAINT PK_Email PRIMARY KEY CLUSTERED
(
	EmailId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE dbo.Email  WITH CHECK ADD  CONSTRAINT FK_Email_EmailType FOREIGN KEY(EmailTypeId)
REFERENCES dbo.EmailType (EmailTypeId)
GO

ALTER TABLE dbo.Email CHECK CONSTRAINT FK_Email_EmailType
GO
