USE [master]
GO

/****** Object:  Database [PeopleTracker]    Script Date: 5/29/2018 5:09:49 PM ******/
DROP DATABASE [PeopleTracker]
GO

CREATE DATABASE [PeopleTracker]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'PeopleTracker', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PeopleTracker.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'PeopleTracker_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PeopleTracker_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PeopleTracker] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PeopleTracker].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PeopleTracker] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [PeopleTracker] SET ANSI_NULLS OFF
GO

ALTER DATABASE [PeopleTracker] SET ANSI_PADDING OFF
GO

ALTER DATABASE [PeopleTracker] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [PeopleTracker] SET ARITHABORT OFF
GO

ALTER DATABASE [PeopleTracker] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [PeopleTracker] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [PeopleTracker] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [PeopleTracker] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [PeopleTracker] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [PeopleTracker] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [PeopleTracker] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [PeopleTracker] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [PeopleTracker] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [PeopleTracker] SET  DISABLE_BROKER
GO

ALTER DATABASE [PeopleTracker] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [PeopleTracker] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [PeopleTracker] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [PeopleTracker] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [PeopleTracker] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [PeopleTracker] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [PeopleTracker] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [PeopleTracker] SET RECOVERY SIMPLE
GO

ALTER DATABASE [PeopleTracker] SET  MULTI_USER
GO

ALTER DATABASE [PeopleTracker] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [PeopleTracker] SET DB_CHAINING OFF
GO

ALTER DATABASE [PeopleTracker] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [PeopleTracker] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [PeopleTracker] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [PeopleTracker] SET QUERY_STORE = OFF
GO

USE [PeopleTracker]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [PeopleTracker] SET  READ_WRITE
GO


