USE PeopleTracker
GO

/****** Object:  Table dbo.Race    Script Date: 6/1/2018 8:38:01 AM ******/
IF OBJECT_ID('dbo.Race', 'U') IS NOT NULL
  DROP TABLE dbo.Race
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.Race
(
  RaceId int IDENTITY(1,1) NOT NULL,
  Description nvarchar(50) NOT NULL,
  CONSTRAINT PK_Race PRIMARY KEY CLUSTERED
(
	RaceId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

