USE [master]
GO

-- NT AUTHORITY\\ANONYMOUS LOGON
-- NT AUTHORITY\IUSR
/****** Object:  Login [NT AUTHORITY\IUSR]    Script Date: 7/21/2018 4:31:35 PM ******/
CREATE LOGIN [NT AUTHORITY\ANONYMOUS LOGON] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT AUTHORITY\ANONYMOUS LOGON]
GO
